language: python
sudo: false
matrix:
  include:
  - python: '3.8'
    sudo: true
    dist: xenial
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install --upgrade coveralls pytest pytest-cov
  - pip install .
script:
  - pytest -v test
  - pytest -v test --backend64